### ISSUE TITLE
Solve problems in microk8s when using port fordwards

### ISSUE THREAD

**Issue by Sergiodfdez** [konstellation-io/kre#102]
When running some scripts to test a runtime, when kre is deployed on microk8s, sometimes show the following error

uid : unable to do port forwarding: socat not found.

**LOGS**
Jun 23 16:34:41 t7k-c4140 microk8s.daemon-containerd[8550]: E0623 16:34:41.454594    8550 httpstream.go:251] error forwarding port 9000 to pod b7a073f7e9f1ac32f90e02b1b89b9f8e65a136f49d2dc08368f698d40961fcb7, uid : failed to execute portforward in network namespace "/var/run/netns/cni-2ce6b3b3-e7a3-98e1-193b-48e4342cf520": socat command returns error: pipe2: too many open files, stderr: ""
Jun 23 16:34:41 t7k-c4140 microk8s.daemon-containerd[8550]: time="2020-06-23T16:34:41.938812504+02:00" level=info msg="Executing port forwarding command "/snap/microk8s/1301/usr/bin/socat - TCP4:localhost:9000" in network namespace "/var/run/netns/cni-2ce6b3b3-e7a3-98e1-193b-48e4342cf520""

**Comment by guumaster** [comment]
migrated to `minikube`
