### ISSUE TITLE
Consider to integrate `developmentMode` flag on UI

### ISSUE THREAD

**Issue by guumaster** [konstellation-io/kre#107]
There is a global flag for KRE called `developmentMode` that setup different things to ease usage during development. 

This variable could be useful to have on the UI to work slightly different during development. Example: remove the need to add comments on actions like start/stop/publish versions.

**Comment by mgs95** [comment]
This variable can be included in the config file `public/config/config.json`.
`ModalContainer` can execute 'Accept' action as soon as it appears if the variable is set to true and a custom hook can be used to manage the form so it sets a default value for 'comment' field.
Should we display a visual clue indicating dev mode is active? like an info bar at the top or something.

**Comment by guumaster** [comment]
> sets a default value for 'comment' field.

Yes, send "development mode" as comment for example.

> Should we display a visual clue indicating dev mode is active? like an info bar at the top or something.

Good idea to show somewhere in the UI that `DEVELOPMENT_MODE` is active.
