### ISSUE TITLE
Add mongodb init script to create initial admin user

### ISSUE THREAD

**Issue by guumaster** [konstellation-io/kre#117]
Upon installation there are no users on the DB. Adding an init script to mongodb chart can solve this by creating it automatically. 

[more info on bitnami mongodb image](https://github.com/bitnami/bitnami-docker-mongodb#initializing-a-new-instance) and [stable helm chart](https://github.com/helm/charts/tree/master/stable/mongodb)

Linked Issues:
- reload admin pod after creating user on local env #111

**Comment by Sergiodfdez** [comment]
Link #111
