### ISSUE TITLE
Research nats streaming instead of NATS

### ISSUE THREAD

**Issue by Sergiodfdez** [konstellation-io/kre#126]
- Fault-Tolerant
- Ensure message reception
- Check performance
- Big messages

**Comment by angelsanchez** [comment]
https://docs.nats.io/developing-with-nats-streaming/streaming

**When to use NATS Streaming**

NATS streaming is ideal when:

- (We don't need) A historical record of a stream is required. This is when a replay of data
is required by a consumer.
- The last message produced on a stream is required for initialization and
the producer may be offline.
- A-priori knowledge of consumers is not available, but consumers must receive messages. This is often a false assumption.
- Data producers and consumers are highly decoupled. They may be online at different times and consumers must receive messages.
- (We don't need) The data in messages being sent have a lifespan beyond that of the intended application lifespan.
- Applications need to consume data at their own pace.

**Comment by jonasdacruz** [comment]
NATS Streaming is a valid candidate for switch it to stream logs, but NATS it will be the main option for now for the rest.
