### ISSUE TITLE
Make error messages more clear

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kre#144]
Sometimes it is not possible to know what happened.

Example: when creating a runtime with a `space` in the name:
![Captura de pantalla de 2020-09-03 15-46-54](https://user-images.githubusercontent.com/2531787/92123454-f9666400-edfc-11ea-84f1-48c5afe4f37e.png)

Same happens when uploading invalid `krt` files
![Captura de pantalla de 2020-09-10 09-29-38](https://user-images.githubusercontent.com/2531787/92695055-31fbc580-f348-11ea-8a0c-907d82029c05.png)

**Comment by angelsanchez** [comment]
The awful messages for runtime creation should be fixed by #284

**Comment by angelsanchez** [comment]
The messages creating a new version should be improved with #286
