### ISSUE TITLE
better folder structure

### ISSUE THREAD

**Issue by guumaster** [konstellation-io/kre#151]
I think we can have a folder structure that is easier to understand for us and future collaborators. 

Here is my proposal. Basically create two main folders for runtime and admin and classify existing folders there.

```
<root> 
    acceptance-tests
    componets-admin
        admin-ui
        admin-api
        k8s-manager
    components-runtime
        mongo-writer
        operator
        runtime-api
        runners
            kre-entrypoint  (older runtime-entrypoint)
            kre-go   (or kre-go-runner)
            kre-py
    docs
    helm
    libs
    scripts
```

**Comment by jonasdacruz** [comment]
<root> 
    acceptance-tests
    admin
        admin-ui
        admin-api
        k8s-manager
    runtime
        mongo-writer
        k8s-runtime-operator
        runtime-api
     runners
         kre-entrypoint  (older runtime-entrypoint)
         kre-go   (or kre-go-runner)
         kre-py
    docs
    helm
    libs
    scripts
