### ISSUE TITLE
Extract Konstellation base components to a shared repo

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kre#169]
Now that we are going to start developing other Konstellation tools that will share styles and some components, we should have a common place to store them. A new repo can be created to achieve this and optionally we can make a DS.

It is important to have proper documentation of these elements as they are going to be used in different repositories, we could use some documentation lib such as docz for fast development or we can create a more professional thing such as a design system with storybook.

Another advantage is that we could reduce significantly the amount of TS/CSS code in out Konstellation projects.

- https://www.docz.site/ : Quick documentation using MDX files. Easy to custom and provides a nice interface. It automatically extracts things such as component props or offers a component playground.
- https://storybook.js.org/ : a robust library that offers easy to do documentation, isolation development, add-ons, visual testing... it also offers great free tutorials to use the lib, make a DS or make tests.

**Comment by guumaster** [comment]
I think is ok to split common component to a new place, but not a new repo. A new folder on the current mono-repo.
