### ISSUE TITLE
ctx.metric.save must be flexible to cover scenarios beyond classification metrics.

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kre#184]

**Comment by jonasdacruz** [comment]
Summary:

- ctx.metric.model.save() > replace the current one
- ctx.metric.save() > it will be a new one to save time series metrics in influxdb

```
ctx.metric.model.save(ts, predictedValue, trueValue, error)

ctx.metric.model.save(ts, fields/values, tags)
```

**Comment by mgs95** [comment]
![image](https://user-images.githubusercontent.com/23691885/88271745-e75eb500-ccd7-11ea-96ba-2f85662376b0.png)
