### ISSUE TITLE
MongoDB data lost after stopping minikube

### ISSUE THREAD

**Issue by angelsanchez** [konstellation-io/kre#215]
With a running KRE in minikube:
1. Stop the minikube: `./krectl.sh stop`
2. Start again using: `./krectl.sh dev -v`

After that all data in mongo database is removed.

**Expected**
The stored mongodb data should remain after stopping minikube.

**Comment by guumaster** [comment]
this still happens on local environment with docker driver.

**Comment by guumaster** [comment]
This is an issue related to minikube docker driver, switching to virtualbox solves the issue.
