### ISSUE TITLE
Autogenerate entrypoint code

### ISSUE THREAD

**Issue by Sergiodfdez** [konstellation-io/kre#26]
Based on KRT configuration, create entrypoint code for each uploaded version.
- Delete the entrypoint from the KRT Yaml.
- Use the protofile to generate the entrypoint code on python.

**Comment by guumaster** [comment]
An article on how to write a  plugin to generate code from .proto files:
* [Writing a protoc plugin with google.golang.org/protobuf](https://medium.com/@tim.r.coulson/writing-a-protoc-plugin-with-google-golang-org-protobuf-cd5aa75f5777)
