### ISSUE TITLE
Review how to represent log tabs depending on its version

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kre#348]
We would like to remove possible confusion when viewing logs of another version within one version.

**Comment by mgs95** [comment]
Option A: warning border on opened tab if does not match opened version:
![image](https://user-images.githubusercontent.com/23691885/94692111-73253b00-0332-11eb-95de-222727fee226.png)

Option B: highlight border on tabs that match opened version:
![image](https://user-images.githubusercontent.com/23691885/94692325-b4b5e600-0332-11eb-8656-518d9552017d.png)

Option C: Group tabs by version (and runtime):
![image](https://user-images.githubusercontent.com/23691885/94693850-8507dd80-0334-11eb-8ca8-db7ebb9400df.png)
> Does this option fixes the problem?

Option D: show a warning indicator

**Comment by jonasdacruz** [comment]
Use "Option A" and try to highlight a little bit more using some text color or any other effect easy to apply.
