### ISSUE TITLE
Review Confusion Matrix dimensions when labels are too long

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kre#356]
Actual behavior when labels are long:
![image](https://user-images.githubusercontent.com/23691885/94782014-eed2c680-03ca-11eb-8184-7f4c0fa58e23.png)

Some possible approaches:
- A: short long labels (and show complete on hover):
![image](https://user-images.githubusercontent.com/23691885/94782130-17f35700-03cb-11eb-8d49-925454519599.png)
- B: make the box grow indefinitely with label width:
![image](https://user-images.githubusercontent.com/23691885/94782325-5b4dc580-03cb-11eb-9046-84c394a11342.png)

**Comment by jonasdacruz** [comment]
Truncate labels and allow a tooltip on hover to show the complete label.
Rotate 45 degrees clockwise the bottom labels in order to gain some space and facilitate the readiness.
