### ISSUE TITLE
Ensure the code coverage we show in public is trustable information and it is updated.

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kre#366]

**Comment by danielchg** [comment]
have been reviewed all the subrepos within KRE monorepo and check that all have a pipeline thar run a job to update the Sonar

**Comment by danielchg** [comment]
![image](https://user-images.githubusercontent.com/17329193/95830357-d43c0e00-0d37-11eb-80eb-3dbcb8cea029.png)
