### ISSUE TITLE
Decide if we want to refactor gqlgen resolver to stop use pointers by default

### ISSUE THREAD

**Issue by guumaster** [konstellation-io/kre#370]
We use `gqlgen` tool to generate boilerplate code and implement only the `resolver.go` file. This tool has a long time issue regarding to the use of pointers or plain objects in function signatures. 

More info [here](https://github.com/99designs/gqlgen/issues/375) and [here](https://github.com/99designs/gqlgen/issues/738).

To sum it up, the discussion can be reduced to this:

```
# Optional, set to true if you prefer []*Thing over []Thing
omit_slice_element_pointers: false
```

If we do this, the refactor to lots of internal function signatures would be time consuming but not too complex.

**Comment by frederikhors** [comment]
Yes please.
