### ISSUE TITLE
Create an admin user during the installation of KRE

### ISSUE THREAD

**Issue by Sergiodfdez** [konstellation-io/kre#38]
Link Issues:
- #111 
- #117

**Comment by jonasdacruz** [comment]
Check if, during the installation, a valid email address can be set and tested. I think it will be easier after installation when accessing the UI when there is not an admin user set, the UI can ask for an admin email to create the user. 

Maybe in this use case the system shouldn't take into account any domain restriction.

**Comment by guumaster** [comment]
Moved this comment 

> Check if, during the installation, a valid email address can be set and tested. I think it will be easier after installation when accessing the UI when there is not an admin user set, the UI can ask for an admin email to create the user.
> 
> Maybe in this use case the system shouldn't take into account any domain restriction.

moved to new issue #236
