### ISSUE TITLE
Messages traveling through NATS between processes should be always a Protobuf

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kre#381]
__Idea description___

Currently the messages travelling through NATS are JSON, the main reasons we should switch to Protobuf are:

- Messages Sizes
- Serializations Performance 
- Strong contract between processes to provide Reliability

__Konstellation impact___

I see a very easy way to implement this improvement, it looks like we only need to change 3 files where the serialization is happening:
- kre-entrypoint/src/kre-nats.py
- kre-py/src/kre-nats.py
- kre-go/runner.go

Within the specific language runners the serialization will came already done, because the proto specification must be provided in the KRT.

__Current users impact___

In this case, the new messages protocol totally deprecates the current solution, so in order to use the new version, they will need to update their solutions.

**Comment by angelsanchez** [comment]
The following table shows examples of compressed sizes and the elapsed times for different data:

| Filename              | Size    | Compress Level | Compress Elapsed Time | Compressed Size |
| --------------------- | ------- | -------------- | --------------------- | --------------- |
| tickets/ticket_0.json | 59 KB   | 0              | 0.38ms                | 45 KB           |
| tickets/ticket_0.json | 59 KB   | 1              | 0.23ms                | 4 KB            |
| tickets/ticket_0.json | 59 KB   | 2              | 0.2ms                 | 4 KB            |
| tickets/ticket_0.json | 59 KB   | 3              | 0.24ms                | 4 KB            |
| tickets/ticket_0.json | 59 KB   | 4              | 0.35ms                | 4 KB            |
| tickets/ticket_0.json | 59 KB   | 5              | 0.39ms                | 3 KB            |
| tickets/ticket_0.json | 59 KB   | 6              | 0.47ms                | 3 KB            |
| tickets/ticket_0.json | 59 KB   | 7              | 0.51ms                | 3 KB            |
| tickets/ticket_0.json | 59 KB   | 8              | 0.91ms                | 3 KB            |
| tickets/ticket_0.json | 59 KB   | 9              | 1.09ms                | 3 KB            |
| tickets/ticket_1.json | 178 KB  | 0              | 1.17ms                | 124 KB          |
| tickets/ticket_1.json | 178 KB  | 1              | 0.75ms                | 12 KB           |
| tickets/ticket_1.json | 178 KB  | 2              | 0.82ms                | 12 KB           |
| tickets/ticket_1.json | 178 KB  | 3              | 0.79ms                | 11 KB           |
| tickets/ticket_1.json | 178 KB  | 4              | 1.08ms                | 10 KB           |
| tickets/ticket_1.json | 178 KB  | 5              | 1.1ms                 | 10 KB           |
| tickets/ticket_1.json | 178 KB  | 6              | 1.33ms                | 9 KB            |
| tickets/ticket_1.json | 178 KB  | 7              | 1.53ms                | 9 KB            |
| tickets/ticket_1.json | 178 KB  | 8              | 2.16ms                | 9 KB            |
| tickets/ticket_1.json | 178 KB  | 9              | 3.09ms                | 9 KB            |
| tickets/ticket_2.json | 654 KB  | 0              | 3.46ms                | 490 KB          |
| tickets/ticket_2.json | 654 KB  | 1              | 2.64ms                | 41 KB           |
| tickets/ticket_2.json | 654 KB  | 2              | 2.58ms                | 40 KB           |
| tickets/ticket_2.json | 654 KB  | 3              | 3.24ms                | 36 KB           |
| tickets/ticket_2.json | 654 KB  | 4              | 4.27ms                | 34 KB           |
| tickets/ticket_2.json | 654 KB  | 5              | 4.44ms                | 31 KB           |
| tickets/ticket_2.json | 654 KB  | 6              | 5.46ms                | 30 KB           |
| tickets/ticket_2.json | 654 KB  | 7              | 9.04ms                | 29 KB           |
| tickets/ticket_2.json | 654 KB  | 8              | 9.3ms                 | 29 KB           |
| tickets/ticket_2.json | 654 KB  | 9              | 10.93ms               | 28 KB           |
| tickets/ticket_3.json | 1256 KB | 0              | 7.52ms                | 944 KB          |
| tickets/ticket_3.json | 1256 KB | 1              | 5.77ms                | 80 KB           |
| tickets/ticket_3.json | 1256 KB | 2              | 5.51ms                | 77 KB           |
| tickets/ticket_3.json | 1256 KB | 3              | 5.71ms                | 70 KB           |
| tickets/ticket_3.json | 1256 KB | 4              | 7.82ms                | 65 KB           |
| tickets/ticket_3.json | 1256 KB | 5              | 8.4ms                 | 59 KB           |
| tickets/ticket_3.json | 1256 KB | 6              | 10.95ms               | 58 KB           |
| tickets/ticket_3.json | 1256 KB | 7              | 12.47ms               | 56 KB           |
| tickets/ticket_3.json | 1256 KB | 8              | 18.07ms               | 55 KB           |
| tickets/ticket_3.json | 1256 KB | 9              | 21.84ms               | 55 KB           |
