### ISSUE TITLE
Create Integration Test for "Publish a specific Runtime Version" feature

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kre#389]
This test should be able to check the right publishing of the an existing runtime version:

Existing Runtime:
- Name: Runtime test 01
- Description: This is the runtime test 01

Existing Runtime Version:
- version: runtime-test-v1

**Comment by guumaster** [comment]
We tried this at some point. Maybe we can recover from here: [PR for acceptance test](https://gitlab.com/konstellation/kre-old/-/merge_requests/169)
