### ISSUE TITLE
Review Mettel reported error "An error has been detected when we try to send a message greater than 2MB"

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kre#465]
GRPC ERROR
details: 'Received http2 header with status: 413'
debug_error_string: {"created":"@1614705037.147075483","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":129,"grpc_message":"Received http2 header with status: 413","grpc_status":2,"value":"413"}

KST  LOG  => Workflow: entrypoint Process: entrypoint
Exception on gRPC call : Traceback (most recent call last):  File "/app/src/kre_grpc.py", line 37, in process_message    raw_msg = await stream.recv_message()  File "/usr/local/lib/python3.7/dist-packages/grpclib/server.py", line 135, in recv_message    message = await recv_message(self._stream, self._codec, self._recv_type)  File "/usr/local/lib/python3.7/dist-packages/grpclib/stream.py", line 29, in recv_message    message_bin = await stream.recv_data(message_len)  File "/usr/local/lib/python3.7/dist-packages/grpclib/protocol.py", line 354, in recv_data    return await self.buffer.read(size)  File "/usr/local/lib/python3.7/dist-packages/grpclib/protocol.py", line 95, in read    data, data_size, ack_size = await self._unacked.get()  File "/usr/lib/python3.7/asyncio/queues.py", line 159, in get    await getterconcurrent.futures._base.CancelledError
KST LOG   => Workflow: entrypoint Process: entrypoint
Failed to handle cancellationTraceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/grpclib/server.py", line 440, in request_handler await method_func(stream) File "/usr/local/lib/python3.7/dist-packages/grpclib/utils.py", line 70, in __exit__ raise self._errorgrpclib.exceptions.StreamTerminatedError: Connection lost

**Comment by mgs95** [comment]
https://github.com/googleapis/google-cloud-node/issues/1991#issuecomment-280410515
