### ISSUE TITLE
Unaccessible KRE entrypoint

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kre#468]
We have a new KRE installation (monoruntime mode) for MetTel Email Classification project where I can access the UI, upload a KRT and start/publish it. 

The issue is that I can't consume the published KRT version with any client. I'm trying with grpcurl and get this errors:

Using -insecure parameter (similar to the call used in TNBA project):
cat "./test/email_sample.json" | grpcurl -insecure -d @ entrypoint.kre-email-tagger.kre-dev-email-tagger.mettel-automation.net:443 entrypoint.Entrypoint/GetPrediction

error:
Error invoking method "entrypoint.Entrypoint/GetPrediction": failed to query for service descriptor "entrypoint.Entrypoint": rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

Without -insecure parameter:
cat "./test/email_sample.json" | grpcurl -insecure -d @ entrypoint.kre-email-tagger.kre-dev-email-tagger.mettel-automation.net:443 entrypoint.Entrypoint/GetPrediction

error:
Failed to dial target host "entrypoint.kre-email-tagger.kre-dev-email-tagger.mettel-automation.net:443": x509: certificate is valid for ingress.local, not entrypoint.kre-email-tagger.kre-dev-email-tagger.mettel-automation.net

The same call works in a local environment with parameter -plaintext.

In both cases there are no logs on KRE UI. The url for the UI is:  https://admin.kre-dev-email-tagger.mettel-automation.net/

NOTE: This KRE installation requires IGZ Global VPN active to access.

**Comment by danielchg** [comment]
we have performed some reviews of the helm code and the kre deployment, and we found out that the issue come when the entrypoint URL is showed in the KRE Admin dashboard, an extra level in the subdomain is added, may be by the pass use of multi runtime approach.

The URL currently displayed is `entrypoint.kre-email-tagger.kre-dev-email-tagger.mettel-automation.net` and the good one is    `entrypoint.kre-dev-email-tagger.mettel-automation.net`.

We need to figure this out.
