### ISSUE TITLE
Error permission in admin-api when deploying with hostpath storage.

### ISSUE THREAD

**Issue by IGZangelcostales** [konstellation-io/kre#470]
The admin-api and all KRE pods work well, the error occurs when uploading new KRT file. The log says: "error generating version doc"

Devops task:

- [x] Use init-container to set default path permission for admin-api files

**Comment by guumaster** [comment]
Also in `admin-api` code, the error get overriden without even being logged to the console:

`doc_generator.go` returns the error properly:
```
	g.logger.Infof("[HTTPStaticDocGenerator] Generating doc folder at: %s", destDocFolder)
	err = copy.Copy(docFolder, destDocFolder)
	if err != nil {
		return fmt.Errorf("error copying doc folder: %w", err)
	}
```

function `saveKRTDoc` on `version_interactor.go` hides the error without showing it:
```
		err = i.docGenerator.Generate(versionCreated.Name, docFolder)
		if err != nil {
			errorMessage := "error generating version doc"
			contentErrors = append(contentErrors, fmt.Errorf(errorMessage))
		}
```
This issue made the bug regarding the permissions much more hard to find than having the log printed somewhere.
