### ISSUE TITLE
Remove Prometheus from chart

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kre#568]
Prometheus operator component installation could fail when other Prometheus operator applications are deployed on the same cluster.

**Comment by alpiquero** [comment]
Working on this issue on `fix/remove-prometheus` branch.

All prometheus-operator references removed from Helm chart.

Additional changes needed on `k8s-manager` application.

**Comment by alpiquero** [comment]
Some refactor on `k8s-manager` needed here!

**Comment by alejandrogr** [comment]
Im on it! ty @alpiquero
