### ISSUE TITLE
Define the easiest way to send alerts when the following events happen

### ISSUE THREAD

**Issue by danielchg** [konstellation-io/kre#9]
- When any resource (RAM, CPU …) is using over 80%

- When a pod has restarted

- When an evicted event happens in a pod

- When an error event happens in a pod

**Comment by guumaster** [comment]
Researching how to monitor MongoDB we found this tools:

* [mongodb_exporter](https://github.com/percona/mongodb_exporter), and an example [MongoDB dashboard for Grafana](https://grafana.com/grafana/dashboards/2583) to see how to consume it.

**Comment by guumaster** [comment]
Implemented basic alerts on #277
